class UfBr:

    def __init__(self):
        self.state_dict = {"AC":'12',
                            "AL":'27',
                            "AM":'13',
                            "AP":'16',
                            "BA":'29',
                            "CE":'23',
                            "DF":'53',
                            "ES":'32',
                            "GO":'52',
                            "MA":'21',
                            "MG":'31',
                            "MS":'50',
                            "MT":'51',
                            "PA":'15',
                            "PB":'25',
                            "PE":'26',
                            "PI":'22',
                            "PR":'41',
                            "RJ":'33',
                            "RN":'24',
                            "RO":'11',
                            "RR":'14',
                            "RS":'43',
                            "SC":'42',
                            "SE":'28',
                            "SP":'35',
                            "TO":'17'}
        self.state_name_dict = {"AC":'Acre',
                            "AL":'Alagoas',
                            "AM":'Amazônia',
                            "AP":'Amapá',
                            "BA":'Bahia',
                            "CE":'Ceará',
                            "DF":'Distrito Federal',
                            "ES":'Espirito Santo',
                            "GO":'Goiás',
                            "MA":'Maranhão',
                            "MG":'Minas Gerais',
                            "MS":'Mato Grosso do Sul',
                            "MT":'Mato Grosso',
                            "PA":'Pará',
                            "PB":'Paraíba',
                            "PE":'Pernambuco',
                            "PI":'Piauí',
                            "PR":'Paraná',
                            "RJ":'Rio de Janeiro',
                            "RN":'Rio Grande do Norte',
                            "RO":'Rondônia',
                            "RR":'Roraima',
                            "RS":'Rio Grande do Sul',
                            "SC":'Santa Catarina',
                            "SE":'Sergipe',
                            "SP":'São Paulo',
                            "TO":'Tocantins'}

        self.state_area_dict = {"AC":164123964,
                                "AL":27843295,
                                "AM":1559167889,
                                "AP":142470762,
                                "BA":564760427,
                                "CE":148894441,
                                "DF":5760783,
                                "ES":46074447,
                                "GO":340203329,
                                "MA":329642182,
                                "MG":586521123,
                                "MS":357145534,
                                "MT":903207019,
                                "PA":1245870798,
                                "PB":56467242,
                                "PE":98067881,
                                "PI":251756515,
                                "PR":199298979,
                                "RJ":43750427,
                                "RN":52809602,
                                "RO":23776524,
                                "RR":223644527,
                                "RS":281707156,
                                "SC":95730684,
                                "SE":21925424,
                                "SP":248219481,
                                "TO":277466763}
    
        